### ISSUE TITLE
Unable to use backport

### ISSUE THREAD

**Issue by tobrun** [mapbox/github-release-tools#13]
I'm trying to backport https://github.com/mapbox/mapbox-gl-native/pull/12128 to `release-chai`, but not able to get it working. Probably doing something very trivial wrong here. These are the commands I tried:

`backport ddc4b03c3416f1442a1e177ff5f7de7bf2a8e707 release-chai`

> { Error: 'number' cannot be null
    at values.forEach (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:75:15)
    at Array.forEach (native)
    at Object.keys.forEach.parameterName (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:53:12)
    at Array.forEach (native)
    at validate (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:31:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
  name: 'HttpError',
  code: 400,
  status: 'Bad Request',
  headers: undefined }

`backport https://github.com/mapbox/mapbox-gl-native/pull/12128 release-chai`

> { Error: no reference found for shorthand 'release-chai' errno: -3, errorFunction: 'Reference.dwim' }

`backport #12128 release-chai`

> Not enough non-option arguments: got 0, need at least 2

**Comment by kkaefer** [comment]
I think the error may be that you have ever checked out release-chai locally, so there's no local branch checkout; only a remote.

Backport should use the remote branch as base over the local branch.

**Comment by mourner** [comment]
I made it a bit further, but backport still failed before submitting a PR with:

```
{ HttpError: {"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}
    at response.text.then.message (/Users/mourner/projects/github-release-tools/node_modules/@octokit/rest/lib/request/request.js:78:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HttpError',
  code: 404,
  status: 'Not Found',
  headers: 
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     connection: 'close',
     'content-encoding': 'gzip',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Tue, 10 Jul 2018 15:29:30 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '404 Not Found',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'transfer-encoding': 'chunked',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'D127:77E6:3B0BDEA:89EF0FA:5B44D0DA',
     'x-oauth-scopes': '',
     'x-ratelimit-limit': '5000',
     'x-ratelimit-remaining': '4981',
     'x-ratelimit-reset': '1531238774',
     'x-runtime-rack': '0.047461',
     'x-xss-protection': '1; mode=block' } }
```

**Comment by jfirebaugh** [comment]
@mourner Does your GITHUB_TOKEN have permissions to create a pull request?

**Comment by mourner** [comment]
@jfirebaugh there's nothing mentioning PRs or seeming relevant in the permissions list:

![image](https://user-images.githubusercontent.com/25395/42621844-905df0f8-85c7-11e8-904a-7f18200ca260.png)
