### ISSUE TITLE
Token authentication requires a token to be set

### ISSUE THREAD

**Issue by tobrun** [mapbox/github-release-tools#9]
after installing these tools with npm and running `backport https://github.com/mapbox/mapbox-gl-native/pull/11942 release-boba` . I'm hitting:

```node
Error: Token authentication requires a token to be set
    at authenticate (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/@octokit/rest/lib/plugins/authentication/authenticate.js:26:15)
    at Object.module.exports [as handler] (/usr/local/lib/node_modules/@mapbox/github-release-tools/src/backport.js:7:13)
    at Object.runCommand (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/yargs/yargs.js:1024:28)
    at Object.get [as argv] (/usr/local/lib/node_modules/@mapbox/github-release-tools/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/@mapbox/github-release-tools/bin/backport:26:5)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

Current output doesn't show which authentication token is missing (Github?), the installation instructions do not cover setting up that token.

**Comment by tobrun** [comment]
Tracked it down being a github access token in https://github.com/mapbox/github-release-tools/blob/master/src/backport.js#L7-L10, will add some documentation to the README.md of this repo.

**Comment by tobrun** [comment]
fixed with https://github.com/mapbox/github-release-tools/pull/11
